#!/bin/bash

if ! [ -d ~/users ]; then
        echo "kein ~/users Verzeichnis vorhanden - Abbruch"
        exit 0
fi

PAC=`id -nu`

if [ -d ~/doms ]; then echo; echo "== $PAC =="; ls ~/doms -1; fi

cd ${HOME}/users
for USER in *; do
    cmd="if [ -d ~/doms ]; then echo; echo '== $PAC-$USER =='; ls ~/doms -1; fi"
    echo $cmd | sudo -u "${PAC}-${USER}" bash
done
