#!/bin/bash

if ! [ -d ~/users ]; then
        echo "kein ~/users Verzeichnis vorhanden - Abbruch"
        exit 0
fi

PAC=`id -nu`

cd ${HOME}/users
for USER in *; do
    cmd='if [ -d ~/doms ]; then if [[ ! -z "`find ~/doms -name pri.\*`" ]]; then echo; echo "== `whoami` =="; find ~/doms -name pri.\*; fi; fi'
    echo $cmd | sudo -u "${PAC}-${USER}" bash
done

